sudo: required

services:
    - docker

before_install:
    - docker build -t sujoydipta/docker-react -f Dockerfile.dev .

script:
    - docker run sujoydipta/docker-react npm run test -- --coverage
   